blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/Taiizor/Locale/discussions
    about: Ask questions and discuss ideas
  - name: ðŸ“– Documentation
    url: https://github.com/Taiizor/Locale#readme
    about: Read the documentation before opening an issue